
# Version of the config, don't change it. If you do, you might
# lose all your configurations.
Config Version: 1.0

Settings:
  # Setting to choose how a player opens the belts by default
  # true: Use the F key to open a belt
  # false: Use Shift + F to open a belt
  # Each player can change this personally using /bb hotkey
  Quick Belt by Default: true

  # Setting to choose if player will have the
  # belts enabled by default when the server turns on
  # true: Enabled by default
  # false: Disabled by default
  # Each player can change this personally using /bb toggle
  Enabled by Default: true

# Here you can set the belts available for the server
BlockBelts:
  Oak:
    Materials:
      - OAK_WOOD
      - OAK_LOG
      - STRIPPED_OAK_WOOD
      - STRIPPED_OAK_LOG
      - OAK_PLANKS
      - OAK_STAIRS
      - OAK_SLAB
      - OAK_FENCE
      - OAK_FENCE_GATE
      - OAK_LEAVES
      - OAK_DOOR
      - OAK_TRAPDOOR
      - OAK_SIGN
      - OAK_PRESSURE_PLATE
      - OAK_BUTTON

  Redstone:
    Materials:
      - REDSTONE
      - REDSTONE_TORCH
      - REDSTONE_BLOCK
      - REPEATER
      - COMPARATOR
      - STICKY_PISTON
      - PISTON
      - HONEY_BLOCK
      - SLIME_BLOCK
      - OBSERVER
      - DROPPER
      - DISPENSER
      - TNT
      - NOTE_BLOCK
      - TRAPPED_CHEST
      - CHEST
      - LEVER
      - DAYLIGHT_DETECTOR
      - HOPPER
      - ANVIL
      - CHIPPED_ANVIL
      - DAMAGED_ANVIL
      - CAULDRON
      - IRON_BARS
      - CHAIN
      - LECTERN
      - TARGET
      - TRIPWIRE_HOOK
      - STRING
      - LIGHTNING_ROD

  Spruce:
    Materials:
      - SPRUCE_WOOD
      - SPRUCE_LOG
      - STRIPPED_SPRUCE_WOOD
      - STRIPPED_SPRUCE_LOG
      - SPRUCE_PLANKS
      - SPRUCE_STAIRS
      - SPRUCE_SLAB
      - SPRUCE_FENCE
      - SPRUCE_FENCE_GATE
      - SPRUCE_LEAVES
      - SPRUCE_DOOR
      - SPRUCE_TRAPDOOR
      - SPRUCE_SIGN
      - SPRUCE_PRESSURE_PLATE
      - SPRUCE_BUTTON

  Prismarine:
    Materials:
      - PRISMARINE
      - PRISMARINE_STAIRS
      - PRISMARINE_WALL
      - PRISMARINE_SLAB
      - DARK_PRISMARINE
      - DARK_PRISMARINE_STAIRS
      - DARK_PRISMARINE_SLAB
      - PRISMARINE_BRICKS
      - PRISMARINE_BRICK_STAIRS
      - PRISMARINE_BRICK_SLAB

  Purpur:
    Materials:
      - PURPUR_PILLAR
      - PURPUR_BLOCK
      - PURPUR_STAIRS
      - PURPUR_SLAB

  Terracota:
    Materials:
      - PURPLE_TERRACOTTA
      - MAGENTA_TERRACOTTA
      - PINK_TERRACOTTA
      - RED_TERRACOTTA
      - TERRACOTTA
      - ORANGE_TERRACOTTA
      - WHITE_TERRACOTTA
      - YELLOW_TERRACOTTA
      - LIGHT_GRAY_TERRACOTTA
      - CYAN_TERRACOTTA
      - BROWN_TERRACOTTA
      - GRAY_TERRACOTTA
      - BLACK_TERRACOTTA
      - GREEN_TERRACOTTA
      - LIME_TERRACOTTA
      - BLUE_TERRACOTTA
      - LIGHT_BLUE_TERRACOTTA
      - PURPLE_GLAZED_TERRACOTTA
      - MAGENTA_GLAZED_TERRACOTTA
      - PINK_GLAZED_TERRACOTTA
      - RED_GLAZED_TERRACOTTA
      - ORANGE_GLAZED_TERRACOTTA
      - WHITE_GLAZED_TERRACOTTA
      - YELLOW_GLAZED_TERRACOTTA
      - LIGHT_GRAY_GLAZED_TERRACOTTA
      - CYAN_GLAZED_TERRACOTTA
      - BROWN_GLAZED_TERRACOTTA
      - GRAY_GLAZED_TERRACOTTA
      - BLACK_GLAZED_TERRACOTTA
      - GREEN_GLAZED_TERRACOTTA
      - LIME_GLAZED_TERRACOTTA
      - BLUE_GLAZED_TERRACOTTA
      - LIGHT_BLUE_GLAZED_TERRACOTTA

  Concrete:
    Materials:
      - PURPLE_CONCRETE
      - MAGENTA_CONCRETE
      - PINK_CONCRETE
      - RED_CONCRETE
      - ORANGE_CONCRETE
      - WHITE_CONCRETE
      - YELLOW_CONCRETE
      - LIGHT_GRAY_CONCRETE
      - CYAN_CONCRETE
      - BROWN_CONCRETE
      - GRAY_CONCRETE
      - BLACK_CONCRETE
      - GREEN_CONCRETE
      - LIME_CONCRETE
      - BLUE_CONCRETE
      - LIGHT_BLUE_CONCRETE
      - PURPLE_CONCRETE_POWDER
      - MAGENTA_CONCRETE_POWDER
      - PINK_CONCRETE_POWDER
      - RED_CONCRETE_POWDER
      - ORANGE_CONCRETE_POWDER
      - WHITE_CONCRETE_POWDER
      - YELLOW_CONCRETE_POWDER
      - LIGHT_GRAY_CONCRETE_POWDER
      - CYAN_CONCRETE_POWDER
      - BROWN_CONCRETE_POWDER
      - GRAY_CONCRETE_POWDER
      - BLACK_CONCRETE_POWDER
      - GREEN_CONCRETE_POWDER
      - LIME_CONCRETE_POWDER
      - BLUE_CONCRETE_POWDER
      - LIGHT_BLUE_CONCRETE_POWDER

  Sandstone:
    Materials:
      - CUT_SANDSTONE
      - CUT_SANDSTONE_SLAB
      - SANDSTONE
      - SANDSTONE_STAIRS
      - SANDSTONE_WALL
      - SANDSTONE_SLAB
      - SMOOTH_SANDSTONE
      - SMOOTH_SANDSTONE_STAIRS
      - SMOOTH_SANDSTONE_SLAB
      - CUT_RED_SANDSTONE
      - CUT_RED_SANDSTONE_SLAB
      - RED_SANDSTONE
      - RED_SANDSTONE_STAIRS
      - RED_SANDSTONE_WALL
      - RED_SANDSTONE_SLAB
      - SMOOTH_RED_SANDSTONE
      - SMOOTH_RED_SANDSTONE_STAIRS
      - SMOOTH_RED_SANDSTONE_SLAB
      - CHISELED_SANDSTONE
      - CHISELED_RED_SANDSTONE

  Blackstone:
    Materials:
      - BLACKSTONE
      - BLACKSTONE_STAIRS
      - BLACKSTONE_WALL
      - BLACKSTONE_SLAB
      - POLISHED_BLACKSTONE
      - POLISHED_BLACKSTONE_STAIRS
      - POLISHED_BLACKSTONE_WALL
      - POLISHED_BLACKSTONE_SLAB
      - POLISHED_BLACKSTONE_BUTTON
      - POLISHED_BLACKSTONE_PRESSURE_PLATE
      - CRACKED_POLISHED_BLACKSTONE_BRICKS
      - POLISHED_BLACKSTONE_BRICKS
      - POLISHED_BLACKSTONE_BRICK_STAIRS
      - POLISHED_BLACKSTONE_BRICK_WALL
      - POLISHED_BLACKSTONE_BRICK_SLAB
      - CHISELED_POLISHED_BLACKSTONE
      - GILDED_BLACKSTONE

  Deepslate:
    Materials:
      - CRACKED_DEEPSLATE_BRICKS
      - DEEPSLATE_BRICKS
      - DEEPSLATE_BRICK_STAIRS
      - DEEPSLATE_BRICK_WALL
      - DEEPSLATE_BRICK_SLAB
      - CRACKED_DEEPSLATE_TILES
      - DEEPSLATE_TILES
      - DEEPSLATE_TILE_STAIRS
      - DEEPSLATE_TILE_WALL
      - DEEPSLATE_TILE_SLAB
      - COBBLED_DEEPSLATE
      - COBBLED_DEEPSLATE_STAIRS
      - COBBLED_DEEPSLATE_WALL
      - COBBLED_DEEPSLATE_SLAB
      - POLISHED_DEEPSLATE
      - POLISHED_DEEPSLATE_STAIRS
      - POLISHED_DEEPSLATE_WALL
      - POLISHED_DEEPSLATE_SLAB
      - DEEPSLATE
      - CHISELED_DEEPSLATE

  Ground:
    Materials:
      - MOSS_BLOCK
      - MOSS_CARPET
      - GRASS_BLOCK
      - PODZOL
      - MYCELIUM
      - WARPED_NYLIUM
      - CRIMSON_NYLIUM
      - DIRT
      - COARSE_DIRT
      - ROOTED_DIRT
      - SAND
      - RED_SAND
      - GRAVEL

  Light_source:
    Materials:
      - CANDLE
      - YELLOW_CANDLE
      - ORANGE_CANDLE
      - RED_CANDLE
      - PINK_CANDLE
      - MAGENTA_CANDLE
      - PURPLE_CANDLE
      - BLUE_CANDLE
      - CYAN_CANDLE
      - LIGHT_BLUE_CANDLE
      - LIME_CANDLE
      - GREEN_CANDLE
      - BROWN_CANDLE
      - LIGHT_GRAY_CANDLE
      - GRAY_CANDLE
      - BLACK_CANDLE
      - WHITE_CANDLE
      - LAVA_BUCKET
      - LANTERN
      - CAMPFIRE
      - SOUL_LANTERN
      - SOUL_CAMPFIRE
      - TORCH
      - SOUL_TORCH
      - SEA_LANTERN
      - BEACON
      - END_ROD
      - SHROOMLIGHT
      - GLOWSTONE
      - MAGMA_BLOCK
      - REDSTONE_LAMP

  Nether:
    Materials:
      - RED_NETHER_BRICKS
      - RED_NETHER_BRICK_STAIRS
      - RED_NETHER_BRICK_WALL
      - RED_NETHER_BRICK_SLAB
      - NETHER_BRICKS
      - NETHER_BRICK_STAIRS
      - NETHER_BRICK_WALL
      - NETHER_BRICK_FENCE
      - NETHER_BRICK_SLAB
      - NETHERITE_BLOCK
      - NETHER_WART_BLOCK
      - NETHERRACK
      - CHISELED_NETHER_BRICKS
      - CRACKED_NETHER_BRICKS

  Ice:
    Materials:
      - ICE
      - PACKED_ICE
      - BLUE_ICE

  Saplings:
    Materials:
      - OAK_SAPLING
      - SPRUCE_SAPLING
      - BIRCH_SAPLING
      - JUNGLE_SAPLING
      - ACACIA_SAPLING
      - DARK_OAK_SAPLING

  Birch:
    Materials:
      - BIRCH_WOOD
      - BIRCH_LOG
      - STRIPPED_BIRCH_WOOD
      - STRIPPED_BIRCH_LOG
      - BIRCH_PLANKS
      - BIRCH_STAIRS
      - BIRCH_SLAB
      - BIRCH_FENCE
      - BIRCH_FENCE_GATE
      - BIRCH_LEAVES
      - BIRCH_DOOR
      - BIRCH_TRAPDOOR
      - BIRCH_SIGN
      - BIRCH_PRESSURE_PLATE
      - BIRCH_BUTTON

  Jungle:
    Materials:
      - JUNGLE_WOOD
      - JUNGLE_LOG
      - STRIPPED_JUNGLE_WOOD
      - STRIPPED_JUNGLE_LOG
      - JUNGLE_PLANKS
      - JUNGLE_STAIRS
      - JUNGLE_SLAB
      - JUNGLE_FENCE
      - JUNGLE_FENCE_GATE
      - JUNGLE_LEAVES
      - JUNGLE_DOOR
      - JUNGLE_TRAPDOOR
      - JUNGLE_SIGN
      - JUNGLE_PRESSURE_PLATE
      - JUNGLE_BUTTON

  Acacia:
    Materials:
      - ACACIA_WOOD
      - ACACIA_LOG
      - STRIPPED_ACACIA_WOOD
      - STRIPPED_ACACIA_LOG
      - ACACIA_PLANKS
      - ACACIA_STAIRS
      - ACACIA_SLAB
      - ACACIA_FENCE
      - ACACIA_FENCE_GATE
      - ACACIA_LEAVES
      - ACACIA_DOOR
      - ACACIA_TRAPDOOR
      - ACACIA_SIGN
      - ACACIA_PRESSURE_PLATE
      - ACACIA_BUTTON

  Dark_oak:
    Materials:
      - DARK_OAK_WOOD
      - DARK_OAK_LOG
      - STRIPPED_DARK_OAK_WOOD
      - STRIPPED_DARK_OAK_LOG
      - DARK_OAK_PLANKS
      - DARK_OAK_STAIRS
      - DARK_OAK_SLAB
      - DARK_OAK_FENCE
      - DARK_OAK_FENCE_GATE
      - DARK_OAK_LEAVES
      - DARK_OAK_DOOR
      - DARK_OAK_TRAPDOOR
      - DARK_OAK_SIGN
      - DARK_OAK_PRESSURE_PLATE
      - DARK_OAK_BUTTON

  Crimson:
    Materials:
      - CRIMSON_HYPHAE
      - CRIMSON_STEM
      - STRIPPED_CRIMSON_HYPHAE
      - STRIPPED_CRIMSON_STEM
      - CRIMSON_PLANKS
      - CRIMSON_STAIRS
      - CRIMSON_SLAB
      - CRIMSON_FENCE
      - CRIMSON_FENCE_GATE
      - CRIMSON_DOOR
      - CRIMSON_TRAPDOOR
      - CRIMSON_SIGN
      - CRIMSON_PRESSURE_PLATE
      - CRIMSON_BUTTON

  Warped:
    Materials:
      - WARPED_HYPHAE
      - WARPED_STEM
      - STRIPPED_WARPED_HYPHAE
      - STRIPPED_WARPED_STEM
      - WARPED_PLANKS
      - WARPED_STAIRS
      - WARPED_SLAB
      - WARPED_FENCE
      - WARPED_FENCE_GATE
      - WARPED_DOOR
      - WARPED_TRAPDOOR
      - WARPED_SIGN
      - WARPED_PRESSURE_PLATE
      - WARPED_BUTTON

  Stone:
    Materials:
      - STONE
      - STONE_STAIRS
      - STONE_SLAB
      - STONE_BUTTON
      - SMOOTH_STONE
      - SMOOTH_STONE_SLAB

  Bricks:
    Materials:
      - BRICKS
      - BRICK_STAIRS
      - BRICK_WALL
      - BRICK_SLAB

  Stonebricks:
    Materials:
      - STONE_BRICKS
      - STONE_BRICK_STAIRS
      - STONE_BRICK_SLAB
      - STONE_BRICK_WALL
      - MOSSY_STONE_BRICKS
      - MOSSY_STONE_BRICK_STAIRS
      - MOSSY_STONE_BRICK_SLAB
      - MOSSY_STONE_BRICK_WALL
      - CRACKED_STONE_BRICKS
      - CHISELED_STONE_BRICKS

  Wool:
    Materials:
      - BLACK_WOOL
      - GRAY_WOOL
      - LIGHT_GRAY_WOOL
      - WHITE_WOOL
      - YELLOW_WOOL
      - ORANGE_WOOL
      - RED_WOOL
      - PINK_WOOL
      - MAGENTA_WOOL
      - BLACK_BANNER
      - GRAY_BANNER
      - LIGHT_GRAY_BANNER
      - WHITE_BANNER
      - YELLOW_BANNER
      - ORANGE_BANNER
      - RED_BANNER
      - PINK_BANNER
      - MAGENTA_BANNER
      - BLACK_CARPET
      - GRAY_CARPET
      - LIGHT_GRAY_CARPET
      - WHITE_CARPET
      - YELLOW_CARPET
      - ORANGE_CARPET
      - RED_CARPET
      - PINK_CARPET
      - MAGENTA_CARPET
      - PURPLE_WOOL
      - BLUE_WOOL
      - LIGHT_BLUE_WOOL
      - CYAN_WOOL
      - LIME_WOOL
      - GREEN_WOOL
      - BROWN_WOOL
      - SNOW_BLOCK
      - SNOW
      - PURPLE_BANNER
      - BLUE_BANNER
      - LIGHT_BLUE_BANNER
      - CYAN_BANNER
      - LIME_BANNER
      - GREEN_BANNER
      - BROWN_BANNER
      - POWDER_SNOW_BUCKET
      - SNOWBALL
      - PURPLE_CARPET
      - BLUE_CARPET
      - LIGHT_BLUE_CARPET
      - CYAN_CARPET
      - LIME_CARPET
      - GREEN_CARPET
      - BROWN_CARPET

  Amethyst:
    Materials:
      - AMETHYST_BLOCK
      - BUDDING_AMETHYST
      - AMETHYST_CLUSTER
      - LARGE_AMETHYST_BUD
      - MEDIUM_AMETHYST_BUD
      - SMALL_AMETHYST_BUD

  Bees:
    Materials:
      - BEE_NEST
      - BEE_HIVE
      - HONEYCOMB_BLOCK
      - BEE_SPAWN_EGG

  Cobblestone:
    Materials:
      - COBBLESTONE
      - COBBLESTONE_SLAB
      - COBBLESTONE_WALL
      - COBBLESTONE_STAIRS
      - MOSSY_COBBLESTONE
      - MOSSY_COBBLESTONE_STAIRS
      - MOSSY_COBBLESTONE_WALL
      - MOSSY_COBBLESTONE_SLAB

  Andesite:
    Materials:
      - POLISHED_ANDESITE
      - POLISHED_ANDESITE_SLAB
      - POLISHED_ANDESITE_SLAB
      - ANDESITE
      - ANDESITE_STAIRS
      - ANDESITE_WALL
      - ANDESITE_SLAB

  Diorite:
    Materials:
      - POLISHED_DIORITE
      - POLISHED_DIORITE_SLAB
      - POLISHED_DIORITE_SLAB
      - DIORITE
      - DIORITE_STAIRS
      - DIORITE_WALL
      - DIORITE_SLAB

  Granite:
    Materials:
      - POLISHED_GRANITE
      - POLISHED_GRANITE_SLAB
      - POLISHED_GRANITE_SLAB
      - GRANITE
      - GRANITE_STAIRS
      - GRANITE_WALL
      - GRANITE_SLAB

  Quartz:
    Materials:
      - CHISELED_QUARTZ_BLOCK
      - QUARTZ_BRICKS
      - QUARTZ_BLOCK
      - QUARTZ_STAIRS
      - QUARTZ_SLAB
      - SMOOTH_QUARTZ
      - SMOOTH_QUARTZ_STAIRS
      - SMOOTH_QUARTZ_SLAB
      - QUARTZ_PILLAR

  Coral:
    Materials:
      - TUBE_CORAL_BLOCK
      - DEAD_TUBE_CORAL_BLOCK
      - BRAIN_CORAL_BLOCK
      - DEAD_BRAIN_CORAL_BLOCK
      - BUBBLE_CORAL_BLOCK
      - DEAD_BUBBLE_CORAL_BLOCK
      - FIRE_CORAL_BLOCK
      - DEAD_FIRE_CORAL_BLOCK
      - HORN_CORAL_BLOCK
      - DEAD_HORN_CORAL_BLOCK

  Endstone:
    Materials:
      - END_PORTAL_FRAME
      - END_STONE
      - END_STONE_BRICKS
      - END_STONE_BRICK_STAIRS
      - END_STONE_BRICK_WALL
      - END_STONE_BRICK_SLAB