name: BlockBelt
version: '${project.version}'
main: com.joaquin.blockbelt.BlockBelt
api-version: 1.17
authors: [ Frocoa ]
description: A plugin for builders that allows you to easily change between block groups.